services:
  - type: web
    name: patrimoine-economique
    runtime: node
    plan: free
    buildCommand: 'npm install'
    startCommand: 'npm run server'
    envVars:
      - key: DATA_PATH
        value: ./data/data.json
      - key: PORT
        value: 5000
    autoDeploy: true
